### ISSUE TITLE
Security problems

### ISSUE THREAD

**Issue by mezgoodle** [MaksGovor/WeatherBot#1]
I **saw** you have public *Telegra, token*, *MongoDB pass* and *api-key*. I can advice to use module [dotenv](https://www.npmjs.com/package/dotenv). You'll create environment variables in `.env` files. Also you set them on server. And all your keys will be hidden.
> Add .env to .gitignore.

P.S. For example, look [here](https://github.com/mezgoodle/weather-bot/blob/master/.env_sample) and [here(video)](https://youtu.be/17UVejOw3zA).

**Comment by MaksGovor** [comment]
Thank you, I got it all fixed.
